(()=>{const c=window.COACHHQ_CONFIG,$=x=>document.getElementById(x),redir=`${location.origin}${location.pathname}`,key="coachhq-auth";let all=[],shown=[];const login=$("login"),hero=$("heroLogin"),logout=$("logout"),signedOut=$("signedOut"),app=$("app"),user=$("user"),org=$("org"),team=$("team"),type=$("type"),search=$("search"),refresh=$("refresh"),csv=$("csv"),rows=$("rows"),status=$("status"),error=$("error"),orgCount=$("orgCount"),teamCount=$("teamCount"),recordCount=$("recordCount"),dialog=$("dialog"),json=$("json");login.onclick=hero.onclick=begin;logout.onclick=signout;org.onchange=loadTeams;team.onchange=loadRecords;type.onchange=loadRecords;search.oninput=filter;refresh.onclick=loadRecords;csv.onclick=exportCsv;$("close").onclick=()=>dialog.close();init();
async function init(){try{const q=new URLSearchParams(location.search);if(q.has("error"))throw Error(q.get("error_description")||q.get("error"));if(q.has("code")){await finish(q.get("code"),q.get("state"));history.replaceState({},document.title,redir)}const a=auth();if(a?.idToken&&!expired(a.idToken)){showIn(a.idToken);await loadOrgs()}else showOut()}catch(e){showOut();fail(e.message)}}
async function begin(){const v=random(64),s=random(32),ch=await challenge(v);sessionStorage.setItem("v",v);sessionStorage.setItem("s",s);const p=new URLSearchParams({client_id:c.clientId,response_type:"code",scope:c.scopes.join(" "),redirect_uri:redir,state:s,code_challenge_method:"S256",code_challenge:ch});location.assign(`${c.cognitoDomain}/oauth2/authorize?${p}`)}
async function finish(code,state){const v=sessionStorage.getItem("v");if(!v||state!==sessionStorage.getItem("s"))throw Error("Login response could not be verified.");const b=new URLSearchParams({grant_type:"authorization_code",client_id:c.clientId,code,redirect_uri:redir,code_verifier:v});const r=await fetch(`${c.cognitoDomain}/oauth2/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:b});if(!r.ok)throw Error(`Login failed with HTTP ${r.status}.`);const t=await r.json();localStorage.setItem(key,JSON.stringify({idToken:t.id_token,accessToken:t.access_token}))}
function signout(){localStorage.removeItem(key);location.assign(`${c.cognitoDomain}/logout?${new URLSearchParams({client_id:c.clientId,logout_uri:redir})}`)}
function showIn(t){const d=decode(t);user.textContent=d.email||d["cognito:username"]||"Signed in";signedOut.hidden=true;app.hidden=false;login.hidden=true;logout.hidden=false}
function showOut(){signedOut.hidden=false;app.hidden=true;login.hidden=false;logout.hidden=true}
async function loadOrgs(){try{status.textContent="Loading organizations...";const p=await api("/organizations"),items=p.items||[];orgCount.textContent=items.length;org.innerHTML='<option value="">Select an organization</option>';items.forEach(o=>org.add(new Option(o.organizationName||o.name||o.organizationId,o.organizationId)));status.textContent=items.length?"Select an organization.":"No organizations found."}catch(e){fail(e.message)}}
async function loadTeams(){team.innerHTML='<option value="">Select a team</option>';team.disabled=true;type.disabled=search.disabled=refresh.disabled=csv.disabled=true;all=shown=[];render();if(!org.value)return;try{const p=await api(`/organizations/${encodeURIComponent(org.value)}/teams`),items=p.items||[];teamCount.textContent=items.length;items.forEach(t=>team.add(new Option(t.teamName||t.name||t.teamId,t.teamId)));team.disabled=false;status.textContent=items.length?"Select a team.":"No teams found."}catch(e){fail(e.message)}}
async function loadRecords(){if(!team.value)return;try{status.textContent="Loading records...";const p=await api(`/teams/${encodeURIComponent(team.value)}/records${type.value?`?type=${encodeURIComponent(type.value)}`:""}`);all=p.items||[];type.disabled=search.disabled=refresh.disabled=false;csv.disabled=!all.length;filter();status.textContent=`${all.length} record${all.length===1?"":"s"} loaded.`}catch(e){fail(e.message)}}
function filter(){const q=search.value.toLowerCase().trim();shown=q?all.filter(r=>JSON.stringify(r).toLowerCase().includes(q)):[...all];recordCount.textContent=shown.length;render()}
function render(){rows.innerHTML="";if(!shown.length){rows.innerHTML='<tr><td colspan="5">No matching records.</td></tr>';return}shown.forEach((r,i)=>{const tr=document.createElement("tr"),t=r.entityType||r.SK?.split("#")[0]||"RECORD",n=r.playerName||r.name||r.teamName||r.organizationName||r.evaluatorName||r.recordId||r.playerId||r.SK||"Record";tr.innerHTML=`<td><span class="badge">${esc(t)}</span></td><td>${esc(n)}</td><td>${esc(summary(r))}</td><td>${esc(fmt(r.updatedAt||r.savedAt||""))}</td><td><button class="view">View</button></td>`;tr.querySelector("button").onclick=()=>{json.textContent=JSON.stringify(shown[i],null,2);dialog.showModal()};rows.appendChild(tr)})}
function summary(r){const x=new Set(["PK","SK","entityType","organizationId","teamId","deviceId","appId","updatedAt","collectionName","recordId"]);return Object.entries(r).filter(([k,v])=>!x.has(k)&&v!=null&&typeof v!=="object").slice(0,4).map(([k,v])=>`${k}: ${v}`).join(" • ")}
async function api(path){const a=auth();if(!a?.idToken||expired(a.idToken))throw Error("Session expired. Sign in again.");const r=await fetch(c.apiBaseUrl+path,{headers:{Authorization:a.idToken,Accept:"application/json"}}),text=await r.text();let p={};try{p=text?JSON.parse(text):{}}catch{p={message:text}}if(!r.ok)throw Error(p.message||`HTTP ${r.status}`);return p}
function exportCsv(){const keys=[...shown.reduce((s,r)=>(Object.keys(r).forEach(k=>s.add(k)),s),new Set())],lines=[keys.map(cell).join(","),...shown.map(r=>keys.map(k=>cell(typeof r[k]==="object"?JSON.stringify(r[k]):r[k]??"")).join(","))],blob=new Blob([lines.join("\n")],{type:"text/csv"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="coachhq-records.csv";a.click();URL.revokeObjectURL(u)}
function auth(){try{return JSON.parse(localStorage.getItem(key))}catch{return null}}function decode(t){const p=t.split(".")[1].replace(/-/g,"+").replace(/_/g,"/");return JSON.parse(atob(p.padEnd(p.length+(4-p.length%4)%4,"=")))}function expired(t){try{return Date.now()>=decode(t).exp*1000}catch{return true}}function random(n){const b=new Uint8Array(n);crypto.getRandomValues(b);return Array.from(b,x=>(x%36).toString(36)).join("")}async function challenge(v){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));let s="";for(const x of new Uint8Array(h))s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}function cell(v){return`"${String(v).replace(/"/g,'""')}"`}function fmt(v){if(!v)return"";const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString()}function fail(m){error.hidden=false;error.className="err";error.textContent=m}function esc(v){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
})();